# Generated by Django 4.0 on 2021-12-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('match_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='match.match')),
                ('home_team_moneyline_odds', models.IntegerField()),
                ('away_team_moneyline_odds', models.IntegerField()),
                ('home_team_spread_Line', models.DecimalField(decimal_places=1, max_digits=4)),
                ('away_team_spread_line', models.DecimalField(decimal_places=1, max_digits=4)),
                ('home_team_spread_odds', models.IntegerField()),
                ('away_team_spread_odds', models.IntegerField()),
                ('over_under_line', models.DecimalField(decimal_places=1, max_digits=4)),
                ('over_odds', models.IntegerField()),
                ('under_odds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('match_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='match.match')),
                ('home_team_score', models.SmallIntegerField()),
                ('away_team_score', models.SmallIntegerField()),
                ('moneyline_payout', models.DecimalField(decimal_places=2, max_digits=6)),
                ('spread_payout', models.DecimalField(decimal_places=2, max_digits=6)),
                ('over_under_payout', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sport_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.sport')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='match.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='match.team'),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('match_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='match.match')),
                ('home_team_expected_score', models.DecimalField(decimal_places=5, max_digits=8)),
                ('away_team_expected_score', models.DecimalField(decimal_places=5, max_digits=8)),
                ('moneyline_expected_payout', models.DecimalField(decimal_places=2, max_digits=6)),
                ('spread_expected_payout', models.DecimalField(decimal_places=2, max_digits=6)),
                ('over_under_expected_payout', models.DecimalField(decimal_places=2, max_digits=6)),
                ('moneyline_predicted_winning_team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='match.team')),
                ('over_under_predicted_winning_team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='match.team')),
                ('spread_predicted_winning_team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='match.team')),
            ],
        ),
    ]
